# Run services for the battery operation

version: '3'
services:
    timescaledb:
        image: timescale/timescaledb:latest-pg12
        ports:
          - 5432:5432
        volumes:
          - super_db:/var/lib/postgresql/data
        environment:
          - POSTGRES_PASSWORD=postgres
    battery_module:
        image: salazaem/modules_mqtt_v2:battery_x
        command: -H 172.17.0.1 --mode 1 --enableinverter
    control_module:
        image: salazaem/modules_mqtt_v2:controller_x
        command: -H 172.17.0.1
    dbmanager_module:
        image: salazaem/modules_mqtt_v2:dbmanager_x
        command: -H 172.17.0.1 --dbip 172.17.0.1 --cleardbtable
    forecast_module:
        network_mode: host
        image: salazaem/modules_mqtt_v2:forecast_x
        command: -H 172.17.0.1 --mode 1
volumes:
    super_db:
        external: true
